Square.Square Class Reference
Public Member Functions
void setValue (char x)
char getValue ()
int getPosition ()
String toString ()
Protected Attributes
int m_position
char m_x
Detailed Description
Definition at line 14 of file Square.java.
Member Function Documentation
int Square.Square.getPosition ()
Gets the position of the squares
Returns
position
Definition at line 52 of file Square.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.PlayerTTT.addPiece(), Square.SquareTTT.main(), Square.SquareSnL.main(), and Player.PlayerSnL.setPlayerLocation().
char Square.Square.getValue ()
Gets value for x
Returns
x
Definition at line 40 of file Square.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.aiMovementStrategy(), Square.SquareTTT.main(), Display.DisplayTTT.saveGame(), Game.GameTTT.setMovementAI(), and Game.GameTTT.setMovementHuman().
void Square.Square.setValue (char x)
Sets the values for x
Parameters
x
Definition at line 28 of file Square.java.
References Menu.GameSelector.m_TRACE.
Referenced by Square.SquareTTT.main(), Game.GameTTT.setMovementAI(), Game.GameTTT.setMovementHuman(), and Square.SquareTTT.SquareTTT().
String Square.Square.toString ()
Gets the position of the square and converts it to a string
Returns
the position of s as a string
Definition at line 65 of file Square.java.
References Menu.GameSelector.m_TRACE.
Member Data Documentation
int Square.Square.m_position [protected]
Stores the position of the square on the board
Definition at line 17 of file Square.java.
Referenced by Square.SquareSnL.isMovementSquare(), and Square.SquareSnL.SquareSnL().
char Square.Square.m_x [protected]
Stores what the square is filled with. possible values: ` `, `O` or `X`
Definition at line 22 of file Square.java.
The documentation for this class was generated from the following file:
src/Square/Square.java