Display.DisplaySnL Class Reference
This class displays everything for the SnL game.
Public Member Functions
int[] getCoordinates (int squareNo)
int getXVal (int squareNo)
int getYVal (int squareNo)
DisplaySnL (GameSnL gameSnL, ArrayList< Integer > snakesList, ArrayList< Integer > laddersList, ArrayList< PlayerSnL > players, final Boolean visualization)
void addPlayInterface (JFrame frame)
void saveGame ()
void paintComponent (Graphics graphics)
void paintPlayer (Graphics graphics)
void updateGraphics ()
void updateGraphics (int[] coordinates)
void printPlayer (Graphics graphics, Color playerColor, int squareNo, int lastLocation)
void drawBoard (Graphics graphics)
void printLadders (Graphics graphics, ArrayList< Integer > squares)
void printSnakes (Graphics graphics, ArrayList< Integer > snakes)
void createTimer ()
void displayTimer ()
void winner (JFrame frame)
void run ()
Static Public Attributes
static final int SQUARE_WIDTH = 50
static final int SQUARE_HEIGHT = 50
static final int PIECE_DIAMETER = 20
Private Member Functions
void addRollDice ()
void addDiceActionListener ()
void addPlayerInformation ()
void printPosition ()
void addBackButton ()
void addSaveButton ()
Private Attributes
BufferedImage m_snakeHead
BufferedImage m_snakeTail
BufferedImage ladder
StopWatch m_stopWatch
boolean gameRunning = false
JLabel m_dicePicLabel = new JLabel(new ImageIcon(`null`))
JButton m_saveGameButton = new JButton()
JButton m_backButton = new JButton()
JPanel m_playerInfoPanel
ArrayList< JLabel > m_playerInfo
ArrayList< JLabel > m_playerPos
ArrayList< JLabel > m_playerColour
Detailed Description
This class displays everything for the SnL game.
Definition at line 46 of file DisplaySnL.java.
Constructor & Destructor Documentation
Display.DisplaySnL.DisplaySnL (GameSnL gameSnL, ArrayList< Integer > snakesList, ArrayList< Integer > laddersList, ArrayList< PlayerSnL > players, final Boolean visualization)
Constructor for DisplaySnL
Parameters
gameSnL set to m_GameSnL
snakesList set to m_snakeLocations
laddersList set to m_laddersList
players set to m_players
Definition at line 185 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE.
Member Function Documentation
void Display.DisplaySnL.addBackButton () [private]
adds the Back button to screen setting bounds etc
Definition at line 405 of file DisplaySnL.java.
References Game.GameSnL.frameDispose(), Menu.GameSelector.m_TRACE, and Game.GameSnL.reset().
Referenced by Display.DisplaySnL.addPlayInterface().
void Display.DisplaySnL.addDiceActionListener () [private]
Adds the actionListener for the m_rollDiceBtn
Definition at line 263 of file DisplaySnL.java.
References Game.GameSnL.buttonPush(), Game.GameSnL.getIterator(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addRollDice().
void Display.DisplaySnL.addPlayerInformation () [private]
Sets the playerInfoPanel's bounds and adds the player name's and position's to it in the form of JLabels.
Definition at line 339 of file DisplaySnL.java.
References Game.GameSnL.getPlayer(), Game.GameSnL.getPlayerLocation(), Player.Player.getPlayerName(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addPlayInterface().
void Display.DisplaySnL.addPlayInterface (JFrame frame)
Adds the player name, who's turn it is and the roll dice button to the display
Parameters
frame displays the screen output
Definition at line 204 of file DisplaySnL.java.
References Display.DisplaySnL.addBackButton(), Display.DisplaySnL.addPlayerInformation(), Display.DisplaySnL.addRollDice(), Display.DisplaySnL.addSaveButton(), Display.DisplaySnL.createTimer(), Display.DisplaySnL.displayTimer(), Game.GameSnL.getIterator(), Menu.GameSelector.m_TRACE, Display.DisplaySnL.printPosition(), and Display.DisplaySnL.run().
Referenced by Game.GameSnL.initDisplay().
void Display.DisplaySnL.addRollDice () [private]
Sets the bounds for the m_rollDiceBtn
Definition at line 243 of file DisplaySnL.java.
References Display.DisplaySnL.addDiceActionListener(), Game.GameSnL.getIterator(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addPlayInterface().
void Display.DisplaySnL.addSaveButton () [private]
Sets the save button text and bounds and creates action listener
Definition at line 432 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE, and Display.DisplaySnL.saveGame().
Referenced by Display.DisplaySnL.addPlayInterface().
void Display.DisplaySnL.createTimer ()
Creates the stop watch timer
Definition at line 752 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addPlayInterface().
void Display.DisplaySnL.displayTimer ()
Displays the stopwatch timer
Definition at line 775 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addPlayInterface().
void Display.DisplaySnL.drawBoard (Graphics graphics)
Draws the board
Parameters
graphics
Definition at line 631 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.paintComponent().
int [] Display.DisplaySnL.getCoordinates (int squareNo)
gets the co_ordinates on the board for a particular square
Parameters
squareNo
Definition at line 131 of file DisplaySnL.java.
References Display.DisplaySnL.getXVal(), Display.DisplaySnL.getYVal(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.printLadders(), Display.DisplaySnL.printPlayer(), and Display.DisplaySnL.printSnakes().
int Display.DisplaySnL.getXVal (int squareNo)
Gets the X Value co-ordinate for the squareNo
Parameters
squareNo
Returns
squareNo
Definition at line 154 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.getCoordinates(), and Display.DisplaySnL.getYVal().
int Display.DisplaySnL.getYVal (int squareNo)
Gets the Y Value co-ordinate for the squareNo
Parameters
squareNo
Returns
squareNo
Definition at line 170 of file DisplaySnL.java.
References Display.DisplaySnL.getXVal(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.getCoordinates().
void Display.DisplaySnL.paintComponent (Graphics graphics)
Calls the method to draw the board and snakes and ladders, display timer
Parameters
graphics
Definition at line 521 of file DisplaySnL.java.
References Display.DisplaySnL.drawBoard(), Menu.GameSelector.m_TRACE, Display.DisplaySnL.paintPlayer(), Display.DisplaySnL.printLadders(), and Display.DisplaySnL.printSnakes().
void Display.DisplaySnL.paintPlayer (Graphics graphics)
Paints the player according to their colour and location
Parameters
graphics
Definition at line 546 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE, and Display.DisplaySnL.printPlayer().
Referenced by Display.DisplaySnL.paintComponent(), and Display.DisplaySnL.updateGraphics().
void Display.DisplaySnL.printLadders (Graphics graphics, ArrayList< Integer > squares)
Prints the ladders on the board
Parameters
graphics
squares
Definition at line 667 of file DisplaySnL.java.
References Display.DisplaySnL.getCoordinates(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.paintComponent().
void Display.DisplaySnL.printPlayer (Graphics graphics, Color playerColor, int squareNo, int lastLocation)
Prints the player to the board
Parameters
graphics
playerColor
squareNo
Definition at line 591 of file DisplaySnL.java.
References Display.DisplaySnL.getCoordinates(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.paintPlayer(), and Display.DisplaySnL.updateGraphics().
void Display.DisplaySnL.printPosition () [private]
Prints the players position in a JLabel
Definition at line 396 of file DisplaySnL.java.
References Game.GameSnL.getIterator(), Game.GameSnL.getPlayerLocation(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addPlayInterface().
void Display.DisplaySnL.printSnakes (Graphics graphics, ArrayList< Integer > snakes)
Prints the snakes on the board
Parameters
graphics
snakes
Definition at line 713 of file DisplaySnL.java.
References Display.DisplaySnL.getCoordinates(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.paintComponent().
void Display.DisplaySnL.run ()
Overrides the run method in this runnable class to repeatedly paintComponents as the timer needs to be continuously updated
Definition at line 839 of file DisplaySnL.java.
Referenced by Display.DisplaySnL.addPlayInterface().
void Display.DisplaySnL.saveGame ()
method to save game to the file res/saveSnL.csv
Definition at line 453 of file DisplaySnL.java.
References Game.GameSnL.getNumberOfPlayers(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addSaveButton().
void Display.DisplaySnL.updateGraphics ()
Paints the player to the screen
Definition at line 562 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE, and Display.DisplaySnL.paintPlayer().
Referenced by Player.PlayerSnL.setPlayerLocation().
void Display.DisplaySnL.updateGraphics (int[] coordinates)
Updates the graphics on the screen particularly the player location
Parameters
coordinates holds the coordinates of the location of the player
Definition at line 573 of file DisplaySnL.java.
References Menu.GameSelector.m_TRACE, and Display.DisplaySnL.printPlayer().
void Display.DisplaySnL.winner (JFrame frame)
When there is a winner a frame pops up to show winner frame the frame for the display
Definition at line 786 of file DisplaySnL.java.
References Game.GameSnL.getIterator(), Game.GameSnL.getPlayerLocation(), and Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.winner().
Member Data Documentation
boolean Display.DisplaySnL.gameRunning = false [private]
Boolean to test if game is running
Definition at line 93 of file DisplaySnL.java.
BufferedImage Display.DisplaySnL.ladder [private]
Ladder buffered image
Definition at line 75 of file DisplaySnL.java.
JButton Display.DisplaySnL.m_backButton = new JButton() [private]
Button to go back to main menu
Definition at line 108 of file DisplaySnL.java.
JLabel Display.DisplaySnL.m_dicePicLabel = new JLabel(new ImageIcon(`null`)) [private]
Label for dice image
Definition at line 102 of file DisplaySnL.java.
ArrayList<JLabel> Display.DisplaySnL.m_playerColour [private]
Arraylist to contain player colours
Definition at line 120 of file DisplaySnL.java.
ArrayList<JLabel> Display.DisplaySnL.m_playerInfo [private]
ArrayList to contain player information (names)
Definition at line 114 of file DisplaySnL.java.
JPanel Display.DisplaySnL.m_playerInfoPanel [private]
JPanel to contain player information
Definition at line 111 of file DisplaySnL.java.
ArrayList<JLabel> Display.DisplaySnL.m_playerPos [private]
Arraylist to contain player positions
Definition at line 117 of file DisplaySnL.java.
JButton Display.DisplaySnL.m_saveGameButton = new JButton() [private]
Button to save game
Definition at line 105 of file DisplaySnL.java.
BufferedImage Display.DisplaySnL.m_snakeHead [private]
Snake head buffered image
Definition at line 69 of file DisplaySnL.java.
BufferedImage Display.DisplaySnL.m_snakeTail [private]
Snake tail buffered image
Definition at line 72 of file DisplaySnL.java.
StopWatch Display.DisplaySnL.m_stopWatch [private]
Stop watch variable to display timer
Definition at line 87 of file DisplaySnL.java.
final int Display.DisplaySnL.PIECE_DIAMETER = 20 [static]
Sets shape's diameter
Definition at line 56 of file DisplaySnL.java.
final int Display.DisplaySnL.SQUARE_HEIGHT = 50 [static]
Sets shape's height
Definition at line 53 of file DisplaySnL.java.
final int Display.DisplaySnL.SQUARE_WIDTH = 50 [static]
Sets shape's width
Definition at line 50 of file DisplaySnL.java.
The documentation for this class was generated from the following file:
src/Display/DisplaySnL.java