Menu.MenuSnL Class Reference
The menu class specific to the SnL game This class is for the menu of the SnL game, covering the player colour selection, the number of players and the numbers of snakes and ladders on the board. The menu also allows for the input of player names.
Public Member Functions
MenuSnL ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void addLabels ()
void addNumberOfPlayersComboBox ()
void addPlayersNamesTextField ()
void addColoursComboBox ()
void addPlayerType ()
void addLaddersComboBox ()
void addSnakesComboBox ()
void addVisualizationCheckBox ()
void addLogo ()
void addGameButtons ()
void loadGame ()
void sendForm ()
Private Attributes
final String WINDOW_TITLE = `Snakes and Ladders`
final String[] SNL_NUMBER_PLAYERS
final String[] SNL_COLOR_PLAYERS
final String[] NUMBERS_OF_OPTIONS = { `1`, `2`, `3`, `4` }
final int WINDOW_WIDTH = 500
final int WINDOW_HEIGHT = 550
final String[] HUMAN_OR_AI = {`Human`, `AI`}
final int MAX_NUM_PLAYERS = 4
JFrame m_frame
ArrayList< JTextField > m_playersNameTextField
ArrayList< JComboBox< String > > m_playersColours
ArrayList< JLabel > m_namePlayersLabel
ArrayList< JComboBox< String > > m_playerTypeComboBox
JButton m_initGameButton
JComboBox< String > m_playersComboBox
int m_numberPlayers = 0
JComboBox< String > m_playerSnakes
JComboBox< String > m_playerLadders
int m_snakesNo = 1
int m_laddersNo = 1
JCheckBox visualization
Detailed Description
The menu class specific to the SnL game This class is for the menu of the SnL game, covering the player colour selection, the number of players and the numbers of snakes and ladders on the board. The menu also allows for the input of player names.
Definition at line 49 of file MenuSnL.java.
Constructor & Destructor Documentation
Menu.MenuSnL.MenuSnL ()
This is the MenuSnL constructor. It sets up a new frame setting its height and width.
Definition at line 145 of file MenuSnL.java.
References Menu.MenuSnL.addColoursComboBox(), Menu.MenuSnL.addGameButtons(), Menu.MenuSnL.addLabels(), Menu.MenuSnL.addLaddersComboBox(), Menu.MenuSnL.addLogo(), Menu.MenuSnL.addNumberOfPlayersComboBox(), Menu.MenuSnL.addPlayersNamesTextField(), Menu.MenuSnL.addPlayerType(), Menu.MenuSnL.addSnakesComboBox(), Menu.MenuSnL.addVisualizationCheckBox(), and Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuSnL.main().
Member Function Documentation
void Menu.MenuSnL.addColoursComboBox () [private]
Adds the combo box to the screen to select the player's colours.
Definition at line 281 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuSnL.MAX_NUM_PLAYERS.
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addGameButtons () [private]
Adds the start, load and back button to the frame.
Definition at line 405 of file MenuSnL.java.
References Menu.MenuSnL.loadGame(), Menu.GameSelector.m_TRACE, and Menu.MenuSnL.sendForm().
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addLabels () [private]
Adds the labels on the frame for the title, number of players, number of snakes, number of ladders.
Definition at line 177 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuSnL.MAX_NUM_PLAYERS.
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addLaddersComboBox () [private]
Adds the combo box to the frame to select the number of ladders.
Definition at line 320 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuSnL.NUMBERS_OF_OPTIONS.
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addLogo () [private]
Adds the snakes and ladders logo to the frame.
Definition at line 389 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addNumberOfPlayersComboBox () [private]
Creates a combo box to select the number of players.
Definition at line 217 of file MenuSnL.java.
References Menu.MenuSnL.m_numberPlayers, Menu.GameSelector.m_TRACE, Menu.MenuSnL.MAX_NUM_PLAYERS, and Menu.MenuSnL.SNL_NUMBER_PLAYERS.
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addPlayersNamesTextField () [private]
Adds the text fields to the frame to set the player's names.
Definition at line 265 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuSnL.MAX_NUM_PLAYERS.
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addPlayerType () [private]
Adds the combo box to set the player type
Definition at line 304 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuSnL.MAX_NUM_PLAYERS.
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addSnakesComboBox () [private]
Adds the combo box to the frame to select the number of ladders.
Definition at line 340 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuSnL.NUMBERS_OF_OPTIONS.
Referenced by Menu.MenuSnL.main(), and Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.addVisualizationCheckBox () [private]
Adds the visualization check box to the frame.
Definition at line 360 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuSnL.MenuSnL().
void Menu.MenuSnL.loadGame () [private]
loads the game from the file res/saveSnL
Definition at line 460 of file MenuSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuSnL.addGameButtons(), and Menu.MenuSnL.main().
static void Menu.MenuSnL.main (String[] args) [static]
This is the test method. It calls the menuSnL constructor to add all the correct buttons, all methods are voids so it's impossible to input invalid information. All methods are called, if no load game file available it will try to start the game with no player information throwing an error.
Definition at line 126 of file MenuSnL.java.
References Menu.MenuSnL.addColoursComboBox(), Menu.MenuSnL.addGameButtons(), Menu.MenuSnL.addLabels(), Menu.MenuSnL.addLaddersComboBox(), Menu.MenuSnL.addLogo(), Menu.MenuSnL.addNumberOfPlayersComboBox(), Menu.MenuSnL.addPlayersNamesTextField(), Menu.MenuSnL.addPlayerType(), Menu.MenuSnL.addSnakesComboBox(), Menu.MenuSnL.loadGame(), Menu.MenuSnL.MenuSnL(), and Menu.MenuSnL.sendForm().
void Menu.MenuSnL.sendForm () [private]
Sends the information of all the players and the number of snakes and ladders to GameSnl.
Definition at line 561 of file MenuSnL.java.
References Menu.MenuSnL.m_numberPlayers, and Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuSnL.addGameButtons(), and Menu.MenuSnL.main().
Member Data Documentation
final String [] Menu.MenuSnL.HUMAN_OR_AI = {`Human`, `AI`} [private]
Array to hold the type of players
Definition at line 73 of file MenuSnL.java.
JFrame Menu.MenuSnL.m_frame [private]
Frame for the Snakes and Ladders Menu
Definition at line 81 of file MenuSnL.java.
JButton Menu.MenuSnL.m_initGameButton [private]
Button to start game
Definition at line 96 of file MenuSnL.java.
int Menu.MenuSnL.m_laddersNo = 1 [private]
Number of ladders initialised to 1
Definition at line 114 of file MenuSnL.java.
ArrayList<JLabel> Menu.MenuSnL.m_namePlayersLabel [private]
Array list of player name label
Definition at line 90 of file MenuSnL.java.
int Menu.MenuSnL.m_numberPlayers = 0 [private]
Number of players, initialised to 0
Definition at line 102 of file MenuSnL.java.
Referenced by Menu.MenuSnL.addNumberOfPlayersComboBox(), and Menu.MenuSnL.sendForm().
JComboBox<String> Menu.MenuSnL.m_playerLadders [private]
Combo box to select number of ladders
Definition at line 108 of file MenuSnL.java.
ArrayList<JComboBox<String> > Menu.MenuSnL.m_playersColours [private]
Array List of combo boxes for player's colours
Definition at line 87 of file MenuSnL.java.
JComboBox<String> Menu.MenuSnL.m_playersComboBox [private]
Combo box for players
Definition at line 99 of file MenuSnL.java.
JComboBox<String> Menu.MenuSnL.m_playerSnakes [private]
Combo box to select number of snakes
Definition at line 105 of file MenuSnL.java.
ArrayList<JTextField> Menu.MenuSnL.m_playersNameTextField [private]
Array List of text fields for player's names
Definition at line 84 of file MenuSnL.java.
ArrayList<JComboBox<String> > Menu.MenuSnL.m_playerTypeComboBox [private]
Array list to hold player type
Definition at line 93 of file MenuSnL.java.
int Menu.MenuSnL.m_snakesNo = 1 [private]
Number of snakes initialised to 1
Definition at line 111 of file MenuSnL.java.
final int Menu.MenuSnL.MAX_NUM_PLAYERS = 4 [private]
Maximum number of players
Definition at line 76 of file MenuSnL.java.
Referenced by Menu.MenuSnL.addColoursComboBox(), Menu.MenuSnL.addLabels(), Menu.MenuSnL.addNumberOfPlayersComboBox(), Menu.MenuSnL.addPlayersNamesTextField(), and Menu.MenuSnL.addPlayerType().
final String [] Menu.MenuSnL.NUMBERS_OF_OPTIONS = { `1`, `2`, `3`, `4` } [private]
Array list of numbers to set for snakes/ladders
Definition at line 64 of file MenuSnL.java.
Referenced by Menu.MenuSnL.addLaddersComboBox(), and Menu.MenuSnL.addSnakesComboBox().
final String [] Menu.MenuSnL.SNL_COLOR_PLAYERS [private]
Initial value:
= { " ", "BLUE", "RED",
            "YELLOW", "GREEN"}
Array list of player colour options
Definition at line 60 of file MenuSnL.java.
final String [] Menu.MenuSnL.SNL_NUMBER_PLAYERS [private]
Initial value:
= { " ", "2 players",
            "3 players", "4 players" }
Array list of player number options
Definition at line 56 of file MenuSnL.java.
Referenced by Menu.MenuSnL.addNumberOfPlayersComboBox().
JCheckBox Menu.MenuSnL.visualization [private]
Visualization check box
Definition at line 117 of file MenuSnL.java.
final int Menu.MenuSnL.WINDOW_HEIGHT = 550 [private]
Height of the window
Definition at line 70 of file MenuSnL.java.
final String Menu.MenuSnL.WINDOW_TITLE = `Snakes and Ladders` [private]
Title of the window
Definition at line 53 of file MenuSnL.java.
final int Menu.MenuSnL.WINDOW_WIDTH = 500 [private]
Width of the window
Definition at line 67 of file MenuSnL.java.
The documentation for this class was generated from the following file:
src/Menu/MenuSnL.java