Player.Player Class Reference
Public Member Functions
String getPlayerName ()
void setPlayerName (String name)
Static Public Member Functions
static void main (String[] args)
Protected Attributes
String m_playerName
Detailed Description
Definition at line 19 of file Player.java.
Member Function Documentation
String Player.Player.getPlayerName ()
Gets the player name
Returns
the player name
Definition at line 28 of file Player.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addPlayerInformation(), Display.DisplayTTT.DisplayTTT(), Display.DisplayTTT.doMovementAI(), Display.DisplayTTT.doMovementHuman(), Player.PlayerTTT.main(), and Display.DisplayTTT.playGame().
static void Player.Player.main (String [] args) [static]
main method created for unit testing
Parameters
args
Definition at line 58 of file Player.java.
void Player.Player.setPlayerName (String name)
Sets the player name
Returns
the player name
Definition at line 40 of file Player.java.
References Menu.GameSelector.m_TRACE.
Member Data Documentation
String Player.Player.m_playerName [protected]
The name of the player
Definition at line 22 of file Player.java.
The documentation for this class was generated from the following file:
src/Player/Player.java