Player.PlayerSnL Class Reference
Creates a player for Snakes and Ladders.
Public Member Functions
int getPlayerLocation ()
Color getPlayerColor ()
boolean setPlayerLocation (DisplaySnL displaySnL, Square s, boolean isMovementSquare)
void setLastLocation (int playerLocation)
int getLastLocation ()
ArrayList< Integer > getAllLocations ()
boolean isMovementSquare (SquareSnL s)
Public Attributes
int m_playerLocation = 1
Color m_playerColor
boolean m_isMovementOnSquare
int m_lastLocation
ArrayList< Integer > m_allLocations = new ArrayList<Integer>()
Additional Inherited Members
Detailed Description
Creates a player for Snakes and Ladders.
Definition at line 24 of file PlayerSnL.java.
Member Function Documentation
ArrayList<Integer> Player.PlayerSnL.getAllLocations ()
Definition at line 152 of file PlayerSnL.java.
References Player.PlayerSnL.m_allLocations.
int Player.PlayerSnL.getLastLocation ()
Definition at line 148 of file PlayerSnL.java.
References Player.PlayerSnL.m_lastLocation.
Color Player.PlayerSnL.getPlayerColor ()
get the piece color of player
Returns
piece color
Definition at line 59 of file PlayerSnL.java.
References Player.PlayerSnL.m_playerColor, and Menu.GameSelector.m_TRACE.
int Player.PlayerSnL.getPlayerLocation ()
get the current piece location
Returns
current piece location
Definition at line 46 of file PlayerSnL.java.
References Player.PlayerSnL.m_playerLocation, and Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.checkMove(), and Game.GameSnL.movePlayer().
boolean Player.PlayerSnL.isMovementSquare (SquareSnL s)
check if the piece has moved to destination square
Parameters
s is destination square
Returns
true if piece gets to destination square, or false if not
Definition at line 162 of file PlayerSnL.java.
References Square.SquareSnL.isMovementSquare(), Player.PlayerSnL.m_isMovementOnSquare, and Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.checkMove(), and Game.GameSnL.movePlayer().
void Player.PlayerSnL.setLastLocation (int playerLocation)
Definition at line 143 of file PlayerSnL.java.
Referenced by Game.GameSnL.checkMove().
boolean Player.PlayerSnL.setPlayerLocation (DisplaySnL displaySnL, Square s, boolean isMovementSquare)
if destination square is in the bound then move the piece to destination square
Parameters
displaySnL is current all game information
s is destination square
isMovementSquare to check if the piece is on the destination square or not
Returns
true if piece gets to destination square, or false if the destination is out of bound
Definition at line 79 of file PlayerSnL.java.
References Square.Square.getPosition(), Player.PlayerSnL.m_playerLocation, Menu.GameSelector.m_TRACE, and Display.DisplaySnL.updateGraphics().
Referenced by Game.GameSnL.checkMove(), and Game.GameSnL.movePlayer().
Member Data Documentation
ArrayList<Integer> Player.PlayerSnL.m_allLocations = new ArrayList<Integer>()
Array of positions
Definition at line 39 of file PlayerSnL.java.
Referenced by Player.PlayerSnL.getAllLocations().
boolean Player.PlayerSnL.m_isMovementOnSquare
To check if piece is on the destination square or not
Definition at line 33 of file PlayerSnL.java.
Referenced by Player.PlayerSnL.isMovementSquare().
int Player.PlayerSnL.m_lastLocation
Last location of player
Definition at line 36 of file PlayerSnL.java.
Referenced by Player.PlayerSnL.getLastLocation().
Color Player.PlayerSnL.m_playerColor
The piece color of the player
Definition at line 30 of file PlayerSnL.java.
Referenced by Player.PlayerSnL.getPlayerColor().
int Player.PlayerSnL.m_playerLocation = 1
The piece initial location of the player
Definition at line 27 of file PlayerSnL.java.
Referenced by Player.PlayerSnL.getPlayerLocation(), and Player.PlayerSnL.setPlayerLocation().
The documentation for this class was generated from the following file:
src/Player/PlayerSnL.java