Game.GameSnL Class Reference
Creates all the user interface for Snakes and Ladders, as well as contains all the functions to play the game.
Public Member Functions
int getNumberOfPlayers ()
ArrayList< Integer > getLadders ()
ArrayList< Integer > getSnakes ()
int getPlayerLocation (int playerIndex)
int getPlayersSize ()
int getIterator ()
PlayerSnL getPlayer (int playerIndex)
ArrayList< Integer > getMovementSquares ()
void setSnakes (int i)
void setLadders (int i)
void setMovementSquares (int i)
GameSnL (ArrayList< String > playerNames, ArrayList< Color > playerColors, ArrayList< Integer > playerPositions, ArrayList< Integer > snakes, ArrayList< Integer > ladders, Boolean visualization)
GameSnL (final ArrayList< String > playerNames, final ArrayList< Color > playerColors, final int snakes, final int ladders, final Boolean visualization)
int buttonPush ()
void frameDispose ()
void reset ()
Static Public Member Functions
static int getMovementPair (int original)
static void main (String[] args)
Private Member Functions
void sortPlayers ()
void initVariables (ArrayList< String > playerNames, ArrayList< Color > playerColors, int snakes, int ladders)
void initDisplay ()
int checkMove (PlayerSnL player)
void movePlayer (PlayerSnL player, int destination)
void winner (PlayerSnL player)
int rollDice ()
int[] generateSquares ()
Private Attributes
final int BOARD_WIDTH = 10
final int BOARD_HEIGHT = 10
final int FRAME_HEIGHT = 600
final int FRAME_WIDTH = 800
JFrame m_frame = new JFrame(`Snakes & Ladders`)
final JPanel m_contentPanel = new JPanel()
JLabel m_dicePicLabel = new JLabel(new ImageIcon(`null`))
BufferedImage m_myPicture = null
JFrame m_initialRollFrame = new JFrame()
int[] m_initialRolls
ArrayList< String > m_playerNames
ArrayList< Color > m_playerColors
JTextField m_txtField
JButton m_btnRollDice
JButton m_btnContinue
BoardSnL m_board
int m_playerIterator = 0
DisplaySnL m_shapesPanel
Static Private Attributes
static ArrayList< Integer > m_snakesList = new ArrayList<Integer>()
static ArrayList< Integer > m_laddersList = new ArrayList<Integer>()
static ArrayList< PlayerSnL > players = new ArrayList<PlayerSnL>()
static ArrayList< Integer > m_movementSquares
Detailed Description
Creates all the user interface for Snakes and Ladders, as well as contains all the functions to play the game.
Definition at line 46 of file GameSnL.java.
Constructor & Destructor Documentation
Game.GameSnL.GameSnL (ArrayList< String > playerNames, ArrayList< Color > playerColors, ArrayList< Integer > playerPositions, ArrayList< Integer > snakes, ArrayList< Integer > ladders, Boolean visualization)
Loads data into game
Parameters
playerNames stores the player names.
playerColors shows list of colours.
playerPositions shows list of player positions.
snakes adds snakes to various squares.
ladders adds ladders to various squares.
Definition at line 299 of file GameSnL.java.
References Game.GameSnL.initDisplay().
Referenced by Game.GameSnL.main().
Game.GameSnL.GameSnL (final ArrayList< String > playerNames, final ArrayList< Color > playerColors, final int snakes, final int ladders, final Boolean visualization)
Stores passed data into the game
Parameters
playerNames
all player names.
playerColors
colour of each player.
snakes
number of snakes to be generated.
ladders
number of ladders to be generated.
Definition at line 348 of file GameSnL.java.
References Game.GameSnL.initDisplay(), Game.GameSnL.initVariables(), Game.GameSnL.m_playerIterator, Menu.GameSelector.m_TRACE, and Game.GameSnL.sortPlayers().
Member Function Documentation
int Game.GameSnL.buttonPush ()
Iterates through player turns
Returns
a random number between 1-6
Definition at line 650 of file GameSnL.java.
References Game.GameSnL.checkMove(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addDiceActionListener(), and Game.GameSnL.main().
int Game.GameSnL.checkMove (PlayerSnL player) [private]
Checks if the player has won and checks if the destination is valid
Parameters
player
current player
Returns
a random number from 1-6
Definition at line 566 of file GameSnL.java.
References Player.PlayerSnL.getPlayerLocation(), Board.BoardSnL.getSquare(), Player.PlayerSnL.isMovementSquare(), Menu.GameSelector.m_TRACE, Game.GameSnL.movePlayer(), Game.GameSnL.rollDice(), Player.PlayerSnL.setLastLocation(), Player.PlayerSnL.setPlayerLocation(), and Game.GameSnL.winner().
Referenced by Game.GameSnL.buttonPush(), and Game.GameSnL.main().
void Game.GameSnL.frameDispose ()
Definition at line 727 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addBackButton().
int [] Game.GameSnL.generateSquares () [private]
Generates snake and ladder starting and ending positions
Returns
snake and ladder starting and ending positions
Definition at line 691 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.initVariables(), and Game.GameSnL.main().
int Game.GameSnL.getIterator ()
Returns the current turn
Returns
whose turn it is
Definition at line 199 of file GameSnL.java.
References Game.GameSnL.m_playerIterator, and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addDiceActionListener(), Display.DisplaySnL.addPlayInterface(), Display.DisplaySnL.addRollDice(), Game.GameSnL.main(), Display.DisplaySnL.printPosition(), and Display.DisplaySnL.winner().
ArrayList<Integer> Game.GameSnL.getLadders ()
Returns list of ladders
Returns
list of laddders
Definition at line 146 of file GameSnL.java.
References Game.GameSnL.m_laddersList, and Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.main().
static int Game.GameSnL.getMovementPair (int original) [static]
Generates the squares the player has to move to before and after a snake or a ladder object
Parameters
original
player's initial position
Returns
the squares the player has to move to before and after a snake or a ladder object
Definition at line 245 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Board.BoardSnL.BoardSnL(), and Game.GameSnL.main().
ArrayList<Integer> Game.GameSnL.getMovementSquares ()
Returns the squares the player has to move to before and after a snake or a ladder object
Returns
the squares the player has to move to before and after a snake or a ladder object
Definition at line 228 of file GameSnL.java.
References Game.GameSnL.m_movementSquares, and Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.main().
int Game.GameSnL.getNumberOfPlayers ()
Returns the number of players
Returns
the number of players
Definition at line 133 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.main(), and Display.DisplaySnL.saveGame().
PlayerSnL Game.GameSnL.getPlayer (int playerIndex)
Returns a player name
Parameters
playerIndex
index of player
Returns
player name
Definition at line 214 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addPlayerInformation().
int Game.GameSnL.getPlayerLocation (int playerIndex)
Returns current player's location
Parameters
playerIndex
index of the current player
Returns
the current player's location
Definition at line 174 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplaySnL.addPlayerInformation(), Game.GameSnL.main(), Display.DisplaySnL.printPosition(), and Display.DisplaySnL.winner().
int Game.GameSnL.getPlayersSize ()
Returns the number of players
Returns
the number of players
Definition at line 186 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.main().
ArrayList<Integer> Game.GameSnL.getSnakes ()
Returns list of snakes
Returns
list of snakes
Definition at line 159 of file GameSnL.java.
References Game.GameSnL.m_snakesList, and Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.main().
void Game.GameSnL.initDisplay () [private]
Creates the display
Definition at line 538 of file GameSnL.java.
References Display.DisplaySnL.addPlayInterface(), and Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.GameSnL(), and Game.GameSnL.main().
void Game.GameSnL.initVariables (ArrayList< String > playerNames, ArrayList< Color > playerColors, int snakes, int ladders) [private]
Initialises all the variables and generates the positions of the snakes and ladders
Parameters
playerNames
all player names.
playerColors
colour of each player.
snakes
number of snakes to be generated.
ladders
number of ladders to be generated.
Adds a player object to the player object array list
Generates snake positions
Generates ladder positions
Definition at line 487 of file GameSnL.java.
References Game.GameSnL.generateSquares(), Menu.GameSelector.m_TRACE, Game.GameSnL.setLadders(), Game.GameSnL.setMovementSquares(), and Game.GameSnL.setSnakes().
Referenced by Game.GameSnL.GameSnL(), and Game.GameSnL.main().
static void Game.GameSnL.main (String[] args) [static]
This is the test method. Default values are set for names, colours and number of snakes and ladders.
Definition at line 752 of file GameSnL.java.
References Game.GameSnL.buttonPush(), Game.GameSnL.checkMove(), Game.GameSnL.GameSnL(), Game.GameSnL.generateSquares(), Game.GameSnL.getIterator(), Game.GameSnL.getLadders(), Game.GameSnL.getMovementPair(), Game.GameSnL.getMovementSquares(), Game.GameSnL.getNumberOfPlayers(), Game.GameSnL.getPlayerLocation(), Game.GameSnL.getPlayersSize(), Game.GameSnL.getSnakes(), Board.BoardSnL.getSquare(), Game.GameSnL.initDisplay(), Game.GameSnL.initVariables(), Game.GameSnL.m_board, Game.GameSnL.m_playerIterator, Game.GameSnL.movePlayer(), Game.GameSnL.rollDice(), Game.GameSnL.sortPlayers(), and Game.GameSnL.winner().
void Game.GameSnL.movePlayer (PlayerSnL player, int destination) [private]
Moves the player
Parameters
player
current player
destination
destination square player will get moved to
Definition at line 615 of file GameSnL.java.
References Player.PlayerSnL.getPlayerLocation(), Board.BoardSnL.getSquare(), Player.PlayerSnL.isMovementSquare(), Menu.GameSelector.m_TRACE, and Player.PlayerSnL.setPlayerLocation().
Referenced by Game.GameSnL.checkMove(), and Game.GameSnL.main().
void Game.GameSnL.reset ()
This method resets the board etc to be able to use the back button during game play.
Definition at line 739 of file GameSnL.java.
Referenced by Display.DisplaySnL.addBackButton().
int Game.GameSnL.rollDice () [private]
Rolls the dice
Returns
a random number between 1-6
Definition at line 673 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.checkMove(), and Game.GameSnL.main().
void Game.GameSnL.setLadders (int i)
Sets the position of the ladders
Parameters
i - board position to add ladder to
Definition at line 277 of file GameSnL.java.
Referenced by Game.GameSnL.initVariables().
void Game.GameSnL.setMovementSquares (int i)
Definition at line 281 of file GameSnL.java.
Referenced by Game.GameSnL.initVariables().
void Game.GameSnL.setSnakes (int i)
Sets the position of the snakes
Parameters
i - board position to add snake to
Definition at line 269 of file GameSnL.java.
Referenced by Game.GameSnL.initVariables().
void Game.GameSnL.sortPlayers () [private]
Determines who takes which turn
Definition at line 451 of file GameSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.GameSnL(), and Game.GameSnL.main().
void Game.GameSnL.winner (PlayerSnL player) [private]
Displays winner information in a pop-up
Parameters
player
current player
Definition at line 637 of file GameSnL.java.
References Menu.GameSelector.m_TRACE, and Display.DisplaySnL.winner().
Referenced by Game.GameSnL.checkMove(), and Game.GameSnL.main().
Member Data Documentation
final int Game.GameSnL.BOARD_HEIGHT = 10 [private]
Height of Snakes and Ladders Board
Definition at line 70 of file GameSnL.java.
final int Game.GameSnL.BOARD_WIDTH = 10 [private]
Width of Snakes and Ladders Board
Definition at line 67 of file GameSnL.java.
final int Game.GameSnL.FRAME_HEIGHT = 600 [private]
Height of frame
Definition at line 73 of file GameSnL.java.
final int Game.GameSnL.FRAME_WIDTH = 800 [private]
Width of frame
Definition at line 76 of file GameSnL.java.
BoardSnL Game.GameSnL.m_board [private]
Board object
Definition at line 115 of file GameSnL.java.
Referenced by Game.GameSnL.main().
JButton Game.GameSnL.m_btnContinue [private]
Displays the continue button
Definition at line 112 of file GameSnL.java.
JButton Game.GameSnL.m_btnRollDice [private]
Displays the roll dice button
Definition at line 109 of file GameSnL.java.
final JPanel Game.GameSnL.m_contentPanel = new JPanel() [private]
Panel for player names and positions as well as the dice image
Definition at line 82 of file GameSnL.java.
JLabel Game.GameSnL.m_dicePicLabel = new JLabel(new ImageIcon(`null`)) [private]
Dice image
Definition at line 85 of file GameSnL.java.
JFrame Game.GameSnL.m_frame = new JFrame(`Snakes & Ladders`) [private]
JFrame for displaying the Snakes and Ladders board
Definition at line 79 of file GameSnL.java.
JFrame Game.GameSnL.m_initialRollFrame = new JFrame() [private]
Pop up for initial roll
Definition at line 91 of file GameSnL.java.
int [] Game.GameSnL.m_initialRolls [private]
Initial roll array for player iteration
Definition at line 94 of file GameSnL.java.
ArrayList<Integer> Game.GameSnL.m_laddersList = new ArrayList<Integer>() [static], [private]
Arraylist for ladders
Definition at line 54 of file GameSnL.java.
Referenced by Game.GameSnL.getLadders().
ArrayList<Integer> Game.GameSnL.m_movementSquares [static], [private]
Initial value:
=
            new ArrayList<Integer>()
Arraylist for the squares the player has to move to before and after a snake or a ladder object
Definition at line 63 of file GameSnL.java.
Referenced by Game.GameSnL.getMovementSquares().
BufferedImage Game.GameSnL.m_myPicture = null [private]
Determines what dice photo to display
Definition at line 88 of file GameSnL.java.
ArrayList<Color> Game.GameSnL.m_playerColors [private]
All player colours, whether human or AI
Definition at line 103 of file GameSnL.java.
int Game.GameSnL.m_playerIterator = 0 [private]
Iterator for all players
Definition at line 118 of file GameSnL.java.
Referenced by Game.GameSnL.GameSnL(), Game.GameSnL.getIterator(), and Game.GameSnL.main().
ArrayList<String> Game.GameSnL.m_playerNames [private]
All player names, whether human or AI
Definition at line 100 of file GameSnL.java.
DisplaySnL Game.GameSnL.m_shapesPanel [private]
Panel to display everything
Definition at line 121 of file GameSnL.java.
ArrayList<Integer> Game.GameSnL.m_snakesList = new ArrayList<Integer>() [static], [private]
Arraylist for snakes
Definition at line 51 of file GameSnL.java.
Referenced by Game.GameSnL.getSnakes().
JTextField Game.GameSnL.m_txtField [private]
Displays the player turn
Definition at line 106 of file GameSnL.java.
ArrayList<PlayerSnL> Game.GameSnL.players = new ArrayList<PlayerSnL>() [static], [private]
Arraylist for human player names
Definition at line 57 of file GameSnL.java.
The documentation for this class was generated from the following file:
src/Game/GameSnL.java