Menu.MenuTTT Class Reference
A generic class containing the display methods. This menu class is for the game TTT. The menu allows you to select whether you want to be X or O, as well as having their respective names.
Public Member Functions
MenuTTT ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void addLabels ()
void addPlayerType ()
void addXorOComboBox ()
void addPlayersNamesTextField ()
void addVisualizationCheckBox ()
void addLogo ()
void addGameButtons ()
void loadGame ()
void sendForm ()
Private Attributes
final String WINDOW_TITLE = `Dans Crazy Tic Tac Toe`
final int WINDOW_WIDTH = 500
final int WINDOW_HEIGHT = 370
final String[] TTT_X_OR_O = { ` `, `X`, `O` }
final String[] HUMAN_OR_AI = {`Human`, `AI`}
final int MAX_NUM_PLAYERS = 2
JFrame m_frame
ArrayList< JTextField > m_playersNameTextField
ArrayList< JComboBox< String > > m_playersXorO
ArrayList< JComboBox< String > > m_playerTypeComboBox
ArrayList< JLabel > m_namePlayersLabel
JButton m_initGameButton
JCheckBox visualization
Boolean visualize = false
Detailed Description
A generic class containing the display methods. This menu class is for the game TTT. The menu allows you to select whether you want to be X or O, as well as having their respective names.
Definition at line 50 of file MenuTTT.java.
Constructor & Destructor Documentation
Menu.MenuTTT.MenuTTT ()
This is the constructor for the Tic Tac Toe menu screen. It sets the frame size and adds all the objects.
Definition at line 97 of file MenuTTT.java.
References Menu.MenuTTT.addGameButtons(), Menu.MenuTTT.addLabels(), Menu.MenuTTT.addLogo(), Menu.MenuTTT.addPlayersNamesTextField(), Menu.MenuTTT.addPlayerType(), Menu.MenuTTT.addVisualizationCheckBox(), Menu.MenuTTT.addXorOComboBox(), and Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuTTT.main().
Member Function Documentation
void Menu.MenuTTT.addGameButtons () [private]
Adds the back and start game button to the frame
Definition at line 257 of file MenuTTT.java.
References Menu.MenuTTT.loadGame(), Menu.GameSelector.m_TRACE, and Menu.MenuTTT.sendForm().
Referenced by Menu.MenuTTT.main(), and Menu.MenuTTT.MenuTTT().
void Menu.MenuTTT.addLabels () [private]
Adds the labels to the frame
Definition at line 122 of file MenuTTT.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuTTT.MAX_NUM_PLAYERS.
Referenced by Menu.MenuTTT.main(), and Menu.MenuTTT.MenuTTT().
void Menu.MenuTTT.addLogo () [private]
Adds the logo to the frame
Definition at line 241 of file MenuTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuTTT.main(), and Menu.MenuTTT.MenuTTT().
void Menu.MenuTTT.addPlayersNamesTextField () [private]
Adds the player name text field to the frame
Definition at line 192 of file MenuTTT.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuTTT.MAX_NUM_PLAYERS.
Referenced by Menu.MenuTTT.main(), and Menu.MenuTTT.MenuTTT().
void Menu.MenuTTT.addPlayerType () [private]
Adds the combo box to set the player type to the frame
Definition at line 140 of file MenuTTT.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuTTT.MAX_NUM_PLAYERS.
Referenced by Menu.MenuTTT.main(), and Menu.MenuTTT.MenuTTT().
void Menu.MenuTTT.addVisualizationCheckBox () [private]
Adds the visualization check box to the frame.
Definition at line 209 of file MenuTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuTTT.MenuTTT().
void Menu.MenuTTT.addXorOComboBox () [private]
Adds the combo box with the options X or O to the frame
Definition at line 156 of file MenuTTT.java.
References Menu.GameSelector.m_TRACE, and Menu.MenuTTT.MAX_NUM_PLAYERS.
Referenced by Menu.MenuTTT.main(), and Menu.MenuTTT.MenuTTT().
void Menu.MenuTTT.loadGame () [private]
Loads the saved game from the file res/saveTTT.csv
Definition at line 314 of file MenuTTT.java.
References Display.DisplayTTT.GRID_HEIGHT, Display.DisplayTTT.GRID_WIDTH, Menu.GameSelector.m_TRACE, and Menu.MenuTTT.MAX_NUM_PLAYERS.
Referenced by Menu.MenuTTT.addGameButtons(), and Menu.MenuTTT.main().
static void Menu.MenuTTT.main (String[] args) [static]
This is the test method. It calls the menuTTT constructor to add all the correct buttons, all methods are voids so it's impossible to input invalid information All methods are called, if no load game file available it will try to start the game with no player information throwing an error.
Definition at line 467 of file MenuTTT.java.
References Menu.MenuTTT.addGameButtons(), Menu.MenuTTT.addLabels(), Menu.MenuTTT.addLogo(), Menu.MenuTTT.addPlayersNamesTextField(), Menu.MenuTTT.addPlayerType(), Menu.MenuTTT.addXorOComboBox(), Menu.MenuTTT.loadGame(), Menu.MenuTTT.MenuTTT(), and Menu.MenuTTT.sendForm().
void Menu.MenuTTT.sendForm () [private]
Sends all the player details (name, piece) to GameTTT
Definition at line 389 of file MenuTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Menu.MenuTTT.addGameButtons(), and Menu.MenuTTT.main().
Member Data Documentation
final String [] Menu.MenuTTT.HUMAN_OR_AI = {`Human`, `AI`} [private]
Array to hold player types
Definition at line 65 of file MenuTTT.java.
JFrame Menu.MenuTTT.m_frame [private]
Frame for the tic tac toe menu
Definition at line 71 of file MenuTTT.java.
JButton Menu.MenuTTT.m_initGameButton [private]
Button to initialise game
Definition at line 86 of file MenuTTT.java.
ArrayList<JLabel> Menu.MenuTTT.m_namePlayersLabel [private]
Array list to hold the players name label
Definition at line 83 of file MenuTTT.java.
ArrayList<JTextField> Menu.MenuTTT.m_playersNameTextField [private]
Array list to hold the player's name text fields
Definition at line 74 of file MenuTTT.java.
ArrayList<JComboBox<String> > Menu.MenuTTT.m_playersXorO [private]
Array list to hold player piece options (X or O)
Definition at line 77 of file MenuTTT.java.
ArrayList<JComboBox<String> > Menu.MenuTTT.m_playerTypeComboBox [private]
Array list to hold player type
Definition at line 80 of file MenuTTT.java.
final int Menu.MenuTTT.MAX_NUM_PLAYERS = 2 [private]
Maximum number of players
Definition at line 68 of file MenuTTT.java.
Referenced by Menu.MenuTTT.addLabels(), Menu.MenuTTT.addPlayersNamesTextField(), Menu.MenuTTT.addPlayerType(), Menu.MenuTTT.addXorOComboBox(), and Menu.MenuTTT.loadGame().
final String [] Menu.MenuTTT.TTT_X_OR_O = { ` `, `X`, `O` } [private]
Array to hold values X and O
Definition at line 62 of file MenuTTT.java.
JCheckBox Menu.MenuTTT.visualization [private]
Check box for visualization
Definition at line 89 of file MenuTTT.java.
Boolean Menu.MenuTTT.visualize = false [private]
Boolean for visualization
Definition at line 92 of file MenuTTT.java.
final int Menu.MenuTTT.WINDOW_HEIGHT = 370 [private]
Height of the window
Definition at line 59 of file MenuTTT.java.
final String Menu.MenuTTT.WINDOW_TITLE = `Dans Crazy Tic Tac Toe` [private]
Title of the window
Definition at line 53 of file MenuTTT.java.
final int Menu.MenuTTT.WINDOW_WIDTH = 500 [private]
Width of the window
Definition at line 56 of file MenuTTT.java.
The documentation for this class was generated from the following file:
src/Menu/MenuTTT.java