Display.DisplayTTT Class Reference
This class displays everything for the TTT game.
Classes
class GUIEventHandler
Public Member Functions
void setButtonIcon (int position, char value)
DisplayTTT (GameTTT mygame, Board board, int[] count)
DisplayTTT (GameTTT mygame, Board boardGame, Boolean visualization)
void paintComponent (Graphics graphics)
void run ()
Public Attributes
final int SHAPE_WIDTH = 50
final int SHAPE_HEIGHT = 50
Static Public Attributes
static final int GRID_WIDTH = 8
static final int GRID_HEIGHT = 8
Private Member Functions
void playGame ()
void aiMovementStrategy ()
void doMovementHuman (int squareRef)
void doMovementAI (int randomNumber)
void createTimer ()
void displayTimer ()
void addBackButton ()
void addSaveButton ()
void saveGame ()
void displayTurn ()
void refreshUserUI (String currentTurn)
Private Attributes
ArrayList< Integer > Xs = new ArrayList<Integer>()
ArrayList< Integer > Os = new ArrayList<Integer>()
JFrame frame = new JFrame(`Tic Tac Toe`)
JLabel dispTurn = new JLabel()
JLabel dispPlayers = new JLabel()
JLabel dispCount = new JLabel()
ArrayList< JButton > gridSquares = new ArrayList<JButton>()
int squareRef = 0
JButton m_saveGameButton = new JButton()
ImageIcon animatedGif = new ImageIcon(`res/btnClickedAnim.gif`)
ImageIcon idleImage = new ImageIcon(`res/btnIdleImage.gif`)
JButton goBackButton = new JButton()
StopWatch m_stopWatch
JLabel m_lblTimer = new JLabel(`Timer`)
boolean gameRunning = true
GameTTT game
ArrayList< PlayerTTT > m_players = new ArrayList<PlayerTTT>()
boolean ignoreEvents = false
GUIEventHandler handler = new GUIEventHandler()
boolean playing = true
boolean initialPlay = true
final Random RAND = new Random()
int RANDOM = RAND.nextInt(63)
ArrayList< Integer > m_aiMoves = new ArrayList<Integer>()
Board m_boardGame
Boolean m_visualize = false
Detailed Description
This class displays everything for the TTT game.
Definition at line 50 of file DisplayTTT.java.
Constructor & Destructor Documentation
Display.DisplayTTT.DisplayTTT (GameTTT mygame, Board board, int[] count)
Constructor for displayTTT when load game is called.
Parameters
mygame
board
count
Definition at line 175 of file DisplayTTT.java.
References Display.DisplayTTT.addBackButton(), Display.DisplayTTT.addSaveButton(), Display.DisplayTTT.createTimer(), Display.DisplayTTT.displayTurn(), Player.Player.getPlayerName(), Game.GameTTT.getPlayers(), Game.GameTTT.getPlayerTurn(), Display.DisplayTTT.GRID_HEIGHT, Display.DisplayTTT.GRID_WIDTH, Menu.GameSelector.m_TRACE, Display.DisplayTTT.playGame(), and Display.DisplayTTT.refreshUserUI().
Display.DisplayTTT.DisplayTTT (GameTTT mygame, Board boardGame, Boolean visualization)
Constructor for the displayTTT
Parameters
mygame
boardGame
Definition at line 229 of file DisplayTTT.java.
References Display.DisplayTTT.addBackButton(), Display.DisplayTTT.addSaveButton(), Display.DisplayTTT.createTimer(), Display.DisplayTTT.displayTurn(), Player.Player.getPlayerName(), Game.GameTTT.getPlayers(), Game.GameTTT.getPlayerTurn(), Display.DisplayTTT.GRID_HEIGHT, Display.DisplayTTT.GRID_WIDTH, Menu.GameSelector.m_TRACE, Display.DisplayTTT.playGame(), and Display.DisplayTTT.refreshUserUI().
Member Function Documentation
void Display.DisplayTTT.addBackButton () [private]
adds the Back button to screen setting bounds etc
Definition at line 754 of file DisplayTTT.java.
References Game.GameTTT.frameDispose(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.DisplayTTT().
void Display.DisplayTTT.addSaveButton () [private]
adds the saveButton to the frame
Definition at line 775 of file DisplayTTT.java.
References Menu.GameSelector.m_TRACE, and Display.DisplayTTT.saveGame().
Referenced by Display.DisplayTTT.DisplayTTT().
void Display.DisplayTTT.aiMovementStrategy () [private]
Contains the strategy for the ai player
Definition at line 316 of file DisplayTTT.java.
References Board.Board.accessSquare(), Display.DisplayTTT.doMovementAI(), Game.GameTTT.getBoard(), Square.Square.getValue(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.playGame().
void Display.DisplayTTT.createTimer () [private]
Creates the stop watch timer
Definition at line 724 of file DisplayTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.DisplayTTT().
void Display.DisplayTTT.displayTimer () [private]
Displays the stopwatch timer
Definition at line 746 of file DisplayTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.paintComponent().
void Display.DisplayTTT.displayTurn () [private]
displays the turn of the player, the names of the players playing, and the player's position
Definition at line 836 of file DisplayTTT.java.
References Game.GameTTT.getPlayers(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.DisplayTTT().
void Display.DisplayTTT.doMovementAI (int randomNumber) [private]
This is the method that carries out the random ai movement
Parameters
randomNumber
Definition at line 563 of file DisplayTTT.java.
References Game.GameTTT.frameDispose(), Player.Player.getPlayerName(), Game.GameTTT.getPlayerTurn(), Player.PlayerTTT.isX(), Menu.GameSelector.m_TRACE, Game.GameTTT.nextTurn(), Display.DisplayTTT.refreshUserUI(), Game.GameTTT.setMovementAI(), and Game.GameTTT.winner().
Referenced by Display.DisplayTTT.aiMovementStrategy().
void Display.DisplayTTT.doMovementHuman (int squareRef) [private]
Sets image for any button on the grid dependent on the player moving
Parameters
squareRef this is the reference of the clicked square
Definition at line 409 of file DisplayTTT.java.
References Game.GameTTT.frameDispose(), Game.GameTTT.getCoordinatesWinningSquares(), Player.Player.getPlayerName(), Game.GameTTT.getPlayerTurn(), Player.PlayerTTT.isX(), Menu.GameSelector.m_TRACE, Game.GameTTT.nextTurn(), Display.DisplayTTT.refreshUserUI(), Game.GameTTT.setMovementHuman(), and Game.GameTTT.winner().
Referenced by Display.DisplayTTT.GUIEventHandler.actionPerformed().
void Display.DisplayTTT.paintComponent (Graphics graphics)
Calls the method to display the timer
Parameters
graphics
Definition at line 712 of file DisplayTTT.java.
References Display.DisplayTTT.displayTimer(), and Menu.GameSelector.m_TRACE.
void Display.DisplayTTT.playGame () [private]
plays the game and delays the AI turn
Definition at line 290 of file DisplayTTT.java.
References Display.DisplayTTT.aiMovementStrategy(), Player.Player.getPlayerName(), Game.GameTTT.getPlayerTurn(), and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.GUIEventHandler.actionPerformed(), and Display.DisplayTTT.DisplayTTT().
void Display.DisplayTTT.refreshUserUI (String currentTurn) [private]
Updates the players turn
Definition at line 863 of file DisplayTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.DisplayTTT(), Display.DisplayTTT.doMovementAI(), and Display.DisplayTTT.doMovementHuman().
void Display.DisplayTTT.run ()
override of the run method to paint components while playing game
Definition at line 875 of file DisplayTTT.java.
void Display.DisplayTTT.saveGame () [private]
method to save the game to the file res/saveTTT.csv
Definition at line 797 of file DisplayTTT.java.
References Board.Board.accessSquare(), Square.Square.getValue(), Display.DisplayTTT.GRID_HEIGHT, and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.addSaveButton().
void Display.DisplayTTT.setButtonIcon (int position, char value)
method to set button icon to X or O, used for the load game
Definition at line 151 of file DisplayTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Square.SquareTTT.SquareTTT().
Member Data Documentation
ImageIcon Display.DisplayTTT.animatedGif = new ImageIcon(`res/btnClickedAnim.gif`) [private]
Holds the animated gif for button animation
Definition at line 100 of file DisplayTTT.java.
JLabel Display.DisplayTTT.dispCount = new JLabel() [private]
Label to display count of pieces on board
Definition at line 82 of file DisplayTTT.java.
JLabel Display.DisplayTTT.dispPlayers = new JLabel() [private]
Label to display player name
Definition at line 79 of file DisplayTTT.java.
JLabel Display.DisplayTTT.dispTurn = new JLabel() [private]
Label to display player turn
Definition at line 76 of file DisplayTTT.java.
JFrame Display.DisplayTTT.frame = new JFrame(`Tic Tac Toe`) [private]
JFrame for tic tac toe game
Definition at line 73 of file DisplayTTT.java.
GameTTT Display.DisplayTTT.game [private]
Game object
Definition at line 118 of file DisplayTTT.java.
boolean Display.DisplayTTT.gameRunning = true [private]
Boolean to test if game is running
Definition at line 115 of file DisplayTTT.java.
JButton Display.DisplayTTT.goBackButton = new JButton() [private]
JButton to go back
Definition at line 106 of file DisplayTTT.java.
final int Display.DisplayTTT.GRID_HEIGHT = 8 [static]
Variable to set grid height
Definition at line 70 of file DisplayTTT.java.
Referenced by Display.DisplayTTT.DisplayTTT(), Menu.MenuTTT.loadGame(), Display.DisplayTTT.saveGame(), Board.BoardTTT.winColumn(), Board.BoardTTT.winDiagonalLeft(), Board.BoardTTT.winDiagonalRight(), and Board.BoardTTT.winRow().
final int Display.DisplayTTT.GRID_WIDTH = 8 [static]
Variable to set grid width
Definition at line 67 of file DisplayTTT.java.
Referenced by Display.DisplayTTT.DisplayTTT(), Menu.MenuTTT.loadGame(), Board.BoardTTT.winColumn(), Board.BoardTTT.winDiagonalLeft(), Board.BoardTTT.winDiagonalRight(), and Board.BoardTTT.winRow().
ArrayList<JButton> Display.DisplayTTT.gridSquares = new ArrayList<JButton>() [private]
Array list of Jbuttons to store buttons rendered to the board
Definition at line 85 of file DisplayTTT.java.
GUIEventHandler Display.DisplayTTT.handler = new GUIEventHandler() [private]
event handler for human click
Definition at line 127 of file DisplayTTT.java.
ImageIcon Display.DisplayTTT.idleImage = new ImageIcon(`res/btnIdleImage.gif`) [private]
Holds the idle gif for button animation
Definition at line 103 of file DisplayTTT.java.
boolean Display.DisplayTTT.ignoreEvents = false [private]
boolean to ignore human input when ai's turn
Definition at line 124 of file DisplayTTT.java.
boolean Display.DisplayTTT.initialPlay = true [private]
boolean to detect whether it is the ai's first turn
Definition at line 133 of file DisplayTTT.java.
ArrayList<Integer> Display.DisplayTTT.m_aiMoves = new ArrayList<Integer>() [private]
array list used for the ai moves
Definition at line 142 of file DisplayTTT.java.
Board Display.DisplayTTT.m_boardGame [private]
instance of the board
Definition at line 145 of file DisplayTTT.java.
JLabel Display.DisplayTTT.m_lblTimer = new JLabel(`Timer`) [private]
JLabel to display timer
Definition at line 112 of file DisplayTTT.java.
ArrayList<PlayerTTT> Display.DisplayTTT.m_players = new ArrayList<PlayerTTT>() [private]
Arraylist of the players
Definition at line 121 of file DisplayTTT.java.
JButton Display.DisplayTTT.m_saveGameButton = new JButton() [private]
Button to save game
Definition at line 91 of file DisplayTTT.java.
StopWatch Display.DisplayTTT.m_stopWatch [private]
Stop watch variable to display timer
Definition at line 109 of file DisplayTTT.java.
Boolean Display.DisplayTTT.m_visualize = false [private]
Boolean to detect visualization
Definition at line 148 of file DisplayTTT.java.
ArrayList<Integer> Display.DisplayTTT.Os = new ArrayList<Integer>() [private]
Array list used to hold O values that have been drawn
Definition at line 58 of file DisplayTTT.java.
boolean Display.DisplayTTT.playing = true [private]
boolean to set whether the game is being played or not
Definition at line 130 of file DisplayTTT.java.
final Random Display.DisplayTTT.RAND = new Random() [private]
random used for the ai's turn
Definition at line 136 of file DisplayTTT.java.
int Display.DisplayTTT.RANDOM = RAND.nextInt(63) [private]
random int used for ai's turn
Definition at line 139 of file DisplayTTT.java.
final int Display.DisplayTTT.SHAPE_HEIGHT = 50
Variable to set width of buttons
Definition at line 64 of file DisplayTTT.java.
final int Display.DisplayTTT.SHAPE_WIDTH = 50
Variable to set width of buttons
Definition at line 61 of file DisplayTTT.java.
int Display.DisplayTTT.squareRef = 0 [private]
A numbering for all the squares from 1 to GRID_WIDTH*GRID_HEIGHT
Definition at line 88 of file DisplayTTT.java.
ArrayList<Integer> Display.DisplayTTT.Xs = new ArrayList<Integer>() [private]
Array list used to hold X values that have been drawn
Definition at line 55 of file DisplayTTT.java.
The documentation for this class was generated from the following file:
src/Display/DisplayTTT.java