Square.SquareSnL Class Reference
This class stores the information on each square for SnL.
Public Member Functions
SquareSnL (int position, int destination)
int getDestination ()
boolean isMovementSquare ()
boolean existsPlayer ()
Static Public Member Functions
static void main (String[] args)
Private Attributes
int m_destination
Additional Inherited Members
Detailed Description
This class stores the information on each square for SnL.
Definition at line 16 of file SquareSnL.java.
Constructor & Destructor Documentation
Square.SquareSnL.SquareSnL (int position, int destination)
Sets up the square with the position and destination
Parameters
position
destination
Definition at line 26 of file SquareSnL.java.
References Square.Square.m_position, and Menu.GameSelector.m_TRACE.
Referenced by Square.SquareSnL.main().
Member Function Documentation
boolean Square.SquareSnL.existsPlayer ()
returns whether a player is in the square
Returns
true if there is a player in the square, false if not
Definition at line 64 of file SquareSnL.java.
References Menu.GameSelector.m_TRACE.
int Square.SquareSnL.getDestination ()
returns the destination of this square, possible that destination == position
Returns
destination
Definition at line 40 of file SquareSnL.java.
References Square.SquareSnL.m_destination, and Menu.GameSelector.m_TRACE.
Referenced by Square.SquareSnL.main().
boolean Square.SquareSnL.isMovementSquare ()
Returns whether this square is a movement square
Returns
true if this square is a movement square, false if it is not
Definition at line 52 of file SquareSnL.java.
References Square.SquareSnL.m_destination, Square.Square.m_position, and Menu.GameSelector.m_TRACE.
Referenced by Player.PlayerSnL.isMovementSquare().
static void Square.SquareSnL.main (String[] args) [static]
testing method
Definition at line 73 of file SquareSnL.java.
References Square.SquareSnL.getDestination(), Square.Square.getPosition(), and Square.SquareSnL.SquareSnL().
Member Data Documentation
int Square.SquareSnL.m_destination [private]
Stores the destination of this square if it is a movement square
Definition at line 19 of file SquareSnL.java.
Referenced by Square.SquareSnL.getDestination(), and Square.SquareSnL.isMovementSquare().
The documentation for this class was generated from the following file:
src/Square/SquareSnL.java