Board.BoardSnL Class Reference
the board class for SnL which is a subclass of board, it contains specific methods for the SnL game, such as checking if there is a player on the 100th square
Public Member Functions
SquareSnL getSquare (int i)
BoardSnL (int width, int height, ArrayList< Integer > movementSquares, ArrayList< Integer > laddersList, ArrayList< Integer > snakesList)
int detectEndGame ()
Static Public Member Functions
static void main (String[] args)
Protected Member Functions
void initializeGrid (int width, int height)
Private Attributes
SquareSnL[] m_boardGame
final int FINAL_SQUARE = 100
final int WIN = 1
final int LOSS = 0
Additional Inherited Members
Detailed Description
the board class for SnL which is a subclass of board, it contains specific methods for the SnL game, such as checking if there is a player on the 100th square
Definition at line 28 of file BoardSnL.java.
Constructor & Destructor Documentation
Board.BoardSnL.BoardSnL (int width, int height, ArrayList< Integer > movementSquares, ArrayList< Integer > laddersList, ArrayList< Integer > snakesList)
Constructor for creating the new board, creates new Squares to fill the board, the number of which is width*height
Parameters
width int containing the width of the board to be created
height int containing the height of the board to be created
movementSquares ArrayList of integers containing the position of the ladder bottoms and tail tops (the squares where addition movement occurs)
laddersList ArrayList of integers containing the positions of both the tops and bottoms of ladders.
snakesList ArrayList of integers containing the positions of both the tops and bottoms of snakes.
Definition at line 68 of file BoardSnL.java.
References Game.GameSnL.getMovementPair(), Board.BoardSnL.initializeGrid(), and Menu.GameSelector.m_TRACE.
Referenced by Board.BoardSnL.main().
Member Function Documentation
int Board.BoardSnL.detectEndGame ()
Method for detecting whether the end game has been reached
Returns
int containing 1 if win detected 0 if not.
Definition at line 112 of file BoardSnL.java.
References Board.Board.accessSquare(), Board.BoardSnL.LOSS, Menu.GameSelector.m_TRACE, and Board.BoardSnL.WIN.
Referenced by Board.BoardSnL.main().
SquareSnL Board.BoardSnL.getSquare (int i)
Gives access to a specific square on the board
Parameters
i int containing the position to access
Returns
SquareSnL pointer to the square located at position i
Definition at line 47 of file BoardSnL.java.
References Menu.GameSelector.m_TRACE.
Referenced by Game.GameSnL.checkMove(), Game.GameSnL.main(), and Game.GameSnL.movePlayer().
void Board.BoardSnL.initializeGrid (int width, int height) [protected]
Method that initialises the SnL grid with squares ready for their values to be set
Parameters
width integer containing the width of board to set up
height integer containing the height of board to set up
Definition at line 98 of file BoardSnL.java.
References Board.Board.m_boardHeight, Board.Board.m_boardWidth, and Menu.GameSelector.m_TRACE.
Referenced by Board.BoardSnL.BoardSnL().
static void Board.BoardSnL.main (String[] args) [static]
Test method
Definition at line 129 of file BoardSnL.java.
References Board.BoardSnL.BoardSnL(), and Board.BoardSnL.detectEndGame().
Member Data Documentation
final int Board.BoardSnL.FINAL_SQUARE = 100 [private]
An integer storing the final square on the board
Definition at line 34 of file BoardSnL.java.
final int Board.BoardSnL.LOSS = 0 [private]
integer storing return value for the method detectEndGame
Definition at line 40 of file BoardSnL.java.
Referenced by Board.BoardSnL.detectEndGame().
SquareSnL [] Board.BoardSnL.m_boardGame [private]
The array that stores all the squares used on the board
Definition at line 31 of file BoardSnL.java.
final int Board.BoardSnL.WIN = 1 [private]
integer storing return value for the method detectEndGame
Definition at line 37 of file BoardSnL.java.
Referenced by Board.BoardSnL.detectEndGame().
The documentation for this class was generated from the following file:
src/Board/BoardSnL.java