Player.PlayerTTT Class Reference
Creates a player for TicTacToe.
Public Member Functions
char getPlayerPieceType ()
void setPlayerPieceType (char playerType)
ArrayList< Integer > getPieceLocations ()
int getPieceLocation ()
boolean isX ()
boolean isO ()
void addPiece (Square s)
Static Public Member Functions
static void main (String[] args)
Private Attributes
char m_pieceType
ArrayList< Integer > m_pieceLocations =new ArrayList<Integer>()
Additional Inherited Members
Detailed Description
Creates a player for TicTacToe.
Definition at line 21 of file PlayerTTT.java.
Member Function Documentation
void Player.PlayerTTT.addPiece (Square s)
Add Piece to Piece array
Parameters
s the square location you put the piece on
Definition at line 124 of file PlayerTTT.java.
References Square.Square.getPosition(), and Menu.GameSelector.m_TRACE.
Referenced by Player.PlayerTTT.main().
int Player.PlayerTTT.getPieceLocation ()
get the every piece location integer from 0 to size-1
Returns
most recently placed piece
Definition at line 76 of file PlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.PlayerTTT.main().
ArrayList<Integer> Player.PlayerTTT.getPieceLocations ()
Returns
full set of piece locations
Definition at line 63 of file PlayerTTT.java.
References Player.PlayerTTT.m_pieceLocations, and Menu.GameSelector.m_TRACE.
Referenced by Player.PlayerTTT.main().
char Player.PlayerTTT.getPlayerPieceType ()
Gets the player piece type
Returns
the player piece type is X or O
Definition at line 33 of file PlayerTTT.java.
References Player.PlayerTTT.m_pieceType, and Menu.GameSelector.m_TRACE.
Referenced by Player.PlayerTTT.main().
boolean Player.PlayerTTT.isO ()
Check if the player piece is O or not
Returns
the true if playerPieceType is O
Definition at line 107 of file PlayerTTT.java.
References Player.PlayerTTT.m_pieceType, and Menu.GameSelector.m_TRACE.
Referenced by Player.PlayerTTT.main().
boolean Player.PlayerTTT.isX ()
Check if the player piece is X or not
Returns
the true if playerPieceType is X
Definition at line 90 of file PlayerTTT.java.
References Player.PlayerTTT.m_pieceType, and Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.doMovementAI(), Display.DisplayTTT.doMovementHuman(), Player.PlayerTTT.main(), Game.GameTTT.setMovementAI(), and Game.GameTTT.setMovementHuman().
static void Player.PlayerTTT.main (String [] args) [static]
main method created for unit testing
Parameters
args
Definition at line 137 of file PlayerTTT.java.
References Player.PlayerTTT.addPiece(), Player.PlayerTTT.getPieceLocation(), Player.PlayerTTT.getPieceLocations(), Player.Player.getPlayerName(), Player.PlayerTTT.getPlayerPieceType(), Player.PlayerTTT.isO(), Player.PlayerTTT.isX(), and Player.PlayerTTT.setPlayerPieceType().
void Player.PlayerTTT.setPlayerPieceType (char playerType)
Sets the player piece type
Returns
the player piece type
Definition at line 45 of file PlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.PlayerTTT.main().
Member Data Documentation
ArrayList<Integer> Player.PlayerTTT.m_pieceLocations =new ArrayList<Integer>() [private]
The piece location array of the player
Definition at line 27 of file PlayerTTT.java.
Referenced by Player.PlayerTTT.getPieceLocations().
char Player.PlayerTTT.m_pieceType [private]
The piece type of the player
Definition at line 24 of file PlayerTTT.java.
Referenced by Player.PlayerTTT.getPlayerPieceType(), Player.PlayerTTT.isO(), and Player.PlayerTTT.isX().
The documentation for this class was generated from the following file:
src/Player/PlayerTTT.java