Board.Board Class Reference
Public Member Functions
int getBoardWidth ()
int getBoardHeight ()
Board (int width, int height)
Square accessSquare (int x, int y)
Square accessSquare (int i)
abstract int detectEndGame ()
Protected Attributes
Square[] m_boardGame
int m_boardWidth
int m_boardHeight
Detailed Description
Definition at line 24 of file Board.java.
Constructor & Destructor Documentation
Board.Board.Board (int width, int height)
Constructor for creating a new board
Parameters
width int containing the width of the board to be created
height int containing the height of the board to be created
Definition at line 61 of file Board.java.
References Menu.GameSelector.m_TRACE.
Member Function Documentation
Square Board.Board.accessSquare (int x, int y)
Gives access to a specific square on the board, used for TTT
Parameters
x int containing the x position to access
y int containing the y position to access
Returns
Square type containing the information on the square at coordinates (x,y)
Definition at line 78 of file Board.java.
References Menu.GameSelector.m_TRACE.
Referenced by Display.DisplayTTT.aiMovementStrategy(), Board.BoardTTT.detectEndGame(), Board.BoardSnL.detectEndGame(), Display.DisplayTTT.saveGame(), Game.GameTTT.setMovementAI(), Game.GameTTT.setMovementHuman(), Board.BoardTTT.winColumn(), Board.BoardTTT.winDiagonalLeft(), Board.BoardTTT.winDiagonalRight(), and Board.BoardTTT.winRow().
Square Board.Board.accessSquare (int i)
Gives access to a specific square on the board, used in SnL
Parameters
i int containing the position to access
Returns
Square type containing the information on the square at position i
Definition at line 92 of file Board.java.
References Menu.GameSelector.m_TRACE.
abstract int Board.Board.detectEndGame () [abstract]
Used to detect when the end of the game has been reached, Implementation can be found in child classes.
Returns
int depending on what type of win has been reached
int Board.Board.getBoardHeight ()
gets the Heighth of the board
Returns
int containing the board Height
Definition at line 48 of file Board.java.
References Menu.GameSelector.m_TRACE.
int Board.Board.getBoardWidth ()
gets the width of the board
Returns
int containing the board width
Definition at line 36 of file Board.java.
References Menu.GameSelector.m_TRACE.
Member Data Documentation
Square [] Board.Board.m_boardGame [protected]
The array that stores all the squares used on the board
Definition at line 27 of file Board.java.
Referenced by Board.BoardTTT.BoardTTT().
int Board.Board.m_boardHeight [protected]
Definition at line 30 of file Board.java.
Referenced by Board.BoardTTT.detectEndGame(), and Board.BoardSnL.initializeGrid().
int Board.Board.m_boardWidth [protected]
Variables that store the height and width of the board.
Definition at line 29 of file Board.java.
Referenced by Board.BoardTTT.detectEndGame(), Board.BoardSnL.initializeGrid(), Board.BoardTTT.winColumn(), Board.BoardTTT.winDiagonalLeft(), Board.BoardTTT.winDiagonalRight(), and Board.BoardTTT.winRow().
The documentation for this class was generated from the following file:
src/Board/Board.java