Player.HumanPlayerTTT Class Reference
Creates a human player for TicTacToe.
Public Member Functions
HumanPlayerTTT (String name, char piece)
String getPlayerName ()
char getPlayerPieceType ()
boolean isX ()
boolean isO ()
int getPieceLocation ()
ArrayList< Integer > getPieceLocations ()
void addPiece (Square s)
Static Public Member Functions
static void main (String[] args)
Detailed Description
Creates a human player for TicTacToe.
Definition at line 23 of file HumanPlayerTTT.java.
Constructor & Destructor Documentation
Player.HumanPlayerTTT.HumanPlayerTTT (String name, char piece)
Constructor that save the human player name and piece to the class extends from PlayerTTT
Parameters
name is the player name passed
piece is the player piece passed
Definition at line 31 of file HumanPlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.HumanPlayerTTT.main().
Member Function Documentation
void Player.HumanPlayerTTT.addPiece (Square s)
Add Piece to Piece array extends from PlayerTTT
Parameters
s the square location you put the piece on
Definition at line 128 of file HumanPlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.HumanPlayerTTT.main().
int Player.HumanPlayerTTT.getPieceLocation ()
Gets the player piece location extends from PlayerTTT
Returns
the player one piece location
Definition at line 103 of file HumanPlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.HumanPlayerTTT.main().
ArrayList<Integer> Player.HumanPlayerTTT.getPieceLocations ()
Gets the player piece location array extends from PlayerTTT
Returns
the player one piece location array
Definition at line 115 of file HumanPlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.HumanPlayerTTT.main().
String Player.HumanPlayerTTT.getPlayerName ()
Gets the player name
Returns
the player name extends from Player
Definition at line 45 of file HumanPlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.HumanPlayerTTT.main().
char Player.HumanPlayerTTT.getPlayerPieceType ()
Gets the player piece type extends from playerTTT
Returns
the player piece type is X or O
Definition at line 57 of file HumanPlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.HumanPlayerTTT.main().
boolean Player.HumanPlayerTTT.isO ()
Check if the player piece is O or not
Returns
the true if playerPieceType is O
Definition at line 86 of file HumanPlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.HumanPlayerTTT.main().
boolean Player.HumanPlayerTTT.isX ()
Check if the player piece is X or not
Returns
the true if playerPieceType is X
Definition at line 69 of file HumanPlayerTTT.java.
References Menu.GameSelector.m_TRACE.
Referenced by Player.HumanPlayerTTT.main().
static void Player.HumanPlayerTTT.main (String [] args) [static]
main method created for unit testing
Parameters
args
Definition at line 141 of file HumanPlayerTTT.java.
References Player.HumanPlayerTTT.addPiece(), Player.HumanPlayerTTT.getPieceLocation(), Player.HumanPlayerTTT.getPieceLocations(), Player.HumanPlayerTTT.getPlayerName(), Player.HumanPlayerTTT.getPlayerPieceType(), Player.HumanPlayerTTT.HumanPlayerTTT(), Player.HumanPlayerTTT.isO(), and Player.HumanPlayerTTT.isX().
The documentation for this class was generated from the following file:
src/Player/HumanPlayerTTT.java