Square.SquareTTT Class Reference
This class stores the information on each square for TTT.
Public Member Functions
SquareTTT (int i)
SquareTTT (int i, char value, DisplayTTT display)
Static Public Member Functions
static void main (String[] args)
Additional Inherited Members
Detailed Description
This class stores the information on each square for TTT.
Definition at line 17 of file SquareTTT.java.
Constructor & Destructor Documentation
Square.SquareTTT.SquareTTT (int i)
Constructor for setting up the squares in TTT
Parameters
i
Definition at line 23 of file SquareTTT.java.
References Menu.GameSelector.m_TRACE, and Square.Square.setValue().
Referenced by Square.SquareTTT.main().
Square.SquareTTT.SquareTTT (int i, char value, DisplayTTT display)
Definition at line 33 of file SquareTTT.java.
References Menu.GameSelector.m_TRACE, Display.DisplayTTT.setButtonIcon(), and Square.Square.setValue().
Member Function Documentation
static void Square.SquareTTT.main (String[] args) [static]
Definition at line 44 of file SquareTTT.java.
References Square.Square.getPosition(), Square.Square.getValue(), Square.Square.setValue(), and Square.SquareTTT.SquareTTT().
The documentation for this class was generated from the following file:
src/Square/SquareTTT.java