Board.BoardTTT Class Reference
Specific board class for TTT game board class for TTT which is a subclass of board, this subclass contains methods specific to TTT, such as detecting the win scenario by working out adjacent squares to the players current square.
Public Member Functions
int[] getCoordinatesWinningSquares ()
BoardTTT (int width, int height)
BoardTTT (int width, int height, char[] squareValues, DisplayTTT display)
int detectEndGame ()
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final int DRAW_GAME = -1
static final int NOTHING_HAPPENED = 0
static final int O_WIN = 1
static final int X_WIN = 2
Private Member Functions
Boolean win (char XorO)
Boolean winRow (char XorO)
Boolean winColumn (char XorO)
Boolean winDiagonalRight (char XorO)
Boolean winDiagonalLeft (char XorO)
Private Attributes
int[] m_winningSquareCoordinates = new int[2]
final int WIN_AMOUNT = 5
Additional Inherited Members
Detailed Description
Specific board class for TTT game board class for TTT which is a subclass of board, this subclass contains methods specific to TTT, such as detecting the win scenario by working out adjacent squares to the players current square.
Definition at line 28 of file BoardTTT.java.
Constructor & Destructor Documentation
Board.BoardTTT.BoardTTT (int width, int height)
Constructor for creating a board of length width*height
Parameters
width integer that contains the width of the board to be created
height integer that contains the height of the board to be created
Definition at line 68 of file BoardTTT.java.
References Board.Board.m_boardGame, and Menu.GameSelector.m_TRACE.
Referenced by Board.BoardTTT.main().
Board.BoardTTT.BoardTTT (int width, int height, char[] squareValues, DisplayTTT display)
Constructor for creating a board of length width*height containing already selected square values for use within save/load game
Parameters
width integer that contains the width of the board to be created
height integer that contains the height of the board to be created
squareVales chars that hold the current value of the squares on the board - X, O or ` `.
display the display that they are saved on
Definition at line 89 of file BoardTTT.java.
References Board.Board.m_boardGame, and Menu.GameSelector.m_TRACE.
Member Function Documentation
int Board.BoardTTT.detectEndGame ()
First checks for a draw game by looping though every square and checking if there are any empty squares, if there is not then the game is a draw. It then calls the win() method on both X and O
Definition at line 107 of file BoardTTT.java.
References Board.Board.accessSquare(), Board.BoardTTT.DRAW_GAME, Board.Board.m_boardHeight, Board.Board.m_boardWidth, Menu.GameSelector.m_TRACE, Board.BoardTTT.NOTHING_HAPPENED, Board.BoardTTT.O_WIN, Board.BoardTTT.win(), and Board.BoardTTT.X_WIN.
Referenced by Board.BoardTTT.main(), and Game.GameTTT.winner().
int [] Board.BoardTTT.getCoordinatesWinningSquares ()
Used to return the start and end of the winning chain for output.
Returns
integer array containing the start and end of the winning chain
Definition at line 54 of file BoardTTT.java.
References Menu.GameSelector.m_TRACE, and Board.BoardTTT.m_winningSquareCoordinates.
Referenced by Game.GameTTT.getCoordinatesWinningSquares().
static void Board.BoardTTT.main (String[] args) [static]
Test method
Definition at line 366 of file BoardTTT.java.
References Board.BoardTTT.BoardTTT(), Board.BoardTTT.detectEndGame(), and Board.BoardTTT.win().
Boolean Board.BoardTTT.win (char XorO) [private]
Checks (horizontally, vertically and then diagonally) if there are five Xs or Os (depending on the input) in a row.
Parameters
XorO char containing X or O depending on what type of piece to check win for
Returns
true of false depending on if a win is found.
Definition at line 150 of file BoardTTT.java.
References Menu.GameSelector.m_TRACE, Board.BoardTTT.winColumn(), Board.BoardTTT.winDiagonalLeft(), Board.BoardTTT.winDiagonalRight(), and Board.BoardTTT.winRow().
Referenced by Board.BoardTTT.detectEndGame(), and Board.BoardTTT.main().
Boolean Board.BoardTTT.winColumn (char XorO) [private]
Checks if there is a vertical win
Parameters
XorO the char it is checking for
Returns
true if win is found, false if not
Definition at line 228 of file BoardTTT.java.
References Board.Board.accessSquare(), Display.DisplayTTT.GRID_HEIGHT, Display.DisplayTTT.GRID_WIDTH, Board.Board.m_boardWidth, and Menu.GameSelector.m_TRACE.
Referenced by Board.BoardTTT.win().
Boolean Board.BoardTTT.winDiagonalLeft (char XorO) [private]
Checks if there is a diagonal left win
Parameters
XorO the char it is checking for
Returns
true if win is found, false if not
Definition at line 319 of file BoardTTT.java.
References Board.Board.accessSquare(), Display.DisplayTTT.GRID_HEIGHT, Display.DisplayTTT.GRID_WIDTH, Board.Board.m_boardWidth, and Menu.GameSelector.m_TRACE.
Referenced by Board.BoardTTT.win().
Boolean Board.BoardTTT.winDiagonalRight (char XorO) [private]
Checks if there is a diagonal right win
Parameters
XorO the char it is checking for
Returns
true if win is found, false if not
Definition at line 267 of file BoardTTT.java.
References Board.Board.accessSquare(), Display.DisplayTTT.GRID_HEIGHT, Display.DisplayTTT.GRID_WIDTH, Board.Board.m_boardWidth, and Menu.GameSelector.m_TRACE.
Referenced by Board.BoardTTT.win().
Boolean Board.BoardTTT.winRow (char XorO) [private]
Checks if there is a horizontal win
Parameters
XorO the char it is checking for
Returns
true if win is found, false if not
Definition at line 190 of file BoardTTT.java.
References Board.Board.accessSquare(), Display.DisplayTTT.GRID_HEIGHT, Display.DisplayTTT.GRID_WIDTH, Board.Board.m_boardWidth, and Menu.GameSelector.m_TRACE.
Referenced by Board.BoardTTT.win().
Member Data Documentation
final int Board.BoardTTT.DRAW_GAME = -1 [static]
integer that stores the value for detectEndGame()
Definition at line 39 of file BoardTTT.java.
Referenced by Board.BoardTTT.detectEndGame().
int [] Board.BoardTTT.m_winningSquareCoordinates = new int[2] [private]
Integer array used to store the start and end of the winning chain for output
Definition at line 33 of file BoardTTT.java.
Referenced by Board.BoardTTT.getCoordinatesWinningSquares().
final int Board.BoardTTT.NOTHING_HAPPENED = 0 [static]
integer that stores the value for detectEndGame()
Definition at line 42 of file BoardTTT.java.
Referenced by Board.BoardTTT.detectEndGame().
final int Board.BoardTTT.O_WIN = 1 [static]
integer that stores the value for detectEndGame()
Definition at line 45 of file BoardTTT.java.
Referenced by Board.BoardTTT.detectEndGame().
final int Board.BoardTTT.WIN_AMOUNT = 5 [private]
integer that stores the length of the chain needed to win
Definition at line 36 of file BoardTTT.java.
final int Board.BoardTTT.X_WIN = 2 [static]
integer that stores the value for detectEndGame()
Definition at line 48 of file BoardTTT.java.
Referenced by Board.BoardTTT.detectEndGame().
The documentation for this class was generated from the following file:
src/Board/BoardTTT.java